# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef67fef42d280c981e6f97af8f97cea8d276dedff5e94a3d450a7648f629846e9d863411f58f6ae983b03ba740173d10359b78061e639531c2502cef4c9d4599

test:
  secret_key_base: e999c9b95b6bd5c7c07a972644681db4cdc2d478f8ee4ef493a7ee0fa1d0b77c023e6e7ad075d5ecb3ac7d1469f687d5bb6beebb79f9ffe65b298b89c67b263e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
